(import (class org.junit Test))
(import (class org.junit Assert))
(import (plogger records))

(define-simple-class project-test ()
  ((test-project-record) ::void (@Test)
   (let* ((id "PID")
	  (name "Project Name")
	  (project (make-project id name)))
     (Assert:assertTrue (project? project))
     (Assert:assertEquals id (project-id project))
     (Assert:assertEquals name (project-name project)))))
