(define-library (plogger config)
  (import (kawa base)
          (kawa lib files))
  (export config-path)
  (begin
    (define (config-path)
      (let* ((home (java.lang.System:getProperty "user.home"))
             (path (string-append home "/.plogger")))
        (if (not (file-directory? path))
            (create-directory path))
        path))))
