(define-library (plogger config)
  (import (kawa base)
          (kawa lib files))
  (export config-dir)
  (begin
    (define (config-dir)
      (let* ((home (java.lang.System:getProperty "user.home"))
             (dir (string-append home "/.plogger")))
        (if (not (file-directory? *conf-dir*))
            (create-directory *conf-dir*))
        dir))))
